/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestsNewRouteImport } from './routes/guests/new'
import { Route as GuestsIdRouteImport } from './routes/guests/$id'

const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsNewRoute = GuestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => GuestsRoute,
} as any)
const GuestsIdRoute = GuestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GuestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guests': typeof GuestsRouteWithChildren
  '/guests/$id': typeof GuestsIdRoute
  '/guests/new': typeof GuestsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guests': typeof GuestsRouteWithChildren
  '/guests/$id': typeof GuestsIdRoute
  '/guests/new': typeof GuestsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guests': typeof GuestsRouteWithChildren
  '/guests/$id': typeof GuestsIdRoute
  '/guests/new': typeof GuestsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/guests' | '/guests/$id' | '/guests/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/guests' | '/guests/$id' | '/guests/new'
  id: '__root__' | '/' | '/about' | '/guests' | '/guests/$id' | '/guests/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GuestsRoute: typeof GuestsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests/new': {
      id: '/guests/new'
      path: '/new'
      fullPath: '/guests/new'
      preLoaderRoute: typeof GuestsNewRouteImport
      parentRoute: typeof GuestsRoute
    }
    '/guests/$id': {
      id: '/guests/$id'
      path: '/$id'
      fullPath: '/guests/$id'
      preLoaderRoute: typeof GuestsIdRouteImport
      parentRoute: typeof GuestsRoute
    }
  }
}

interface GuestsRouteChildren {
  GuestsIdRoute: typeof GuestsIdRoute
  GuestsNewRoute: typeof GuestsNewRoute
}

const GuestsRouteChildren: GuestsRouteChildren = {
  GuestsIdRoute: GuestsIdRoute,
  GuestsNewRoute: GuestsNewRoute,
}

const GuestsRouteWithChildren =
  GuestsRoute._addFileChildren(GuestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GuestsRoute: GuestsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
